### PR TITLE
Update API to match v3.26.0

### PR DESCRIPTION
**Pull request by sknat**
This updates the api to match [0] in preparation of 3.26 release

[0] commit d521de4a1c44076b95769e4781b5577aae4bcc38

## Description
Pull in all of the API updates in preparation of Calico v3.26.0

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by sknat** [comment]
@caseydavenport @lwr20 
If you have time to review this, that'd be awesome 😄

**Comment by coutinhop** [comment]
@sknat could you please update `GO_BUILD_VER` to `v0.85` in `metadata.mk` and run `make gen-files` again? I think that'll fix the CI failure

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Pull request merged**
