### PR TITLE
Add MaxRestartTime to BGPPeerSpec (used to BGP graceful restart timer)

### PR DESCRIPTION
**Pull request by coutinhop**
## Description

Add the field MaxRestartTime (Duration) to BGPPeerSpec. This is going to be used to configure the BGP graceful restart timer on BIRD.

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Release note

## Release Note

```release-note
Added MaxRestartTime to BGPPeerSpec (used for BIRD's BGP graceful restart configuration)
```

### CODE REVIEW

**Review by neiljerram — APPROVED** [review]
LGTM, thanks!

**Comment by neiljerram** [comment]
@coutinhop I needed to add a sem-approve comment in order to get CI to run for this PR, but it should have run automatically for you.  I guess that means you haven't been added to all the right teams in GitHub or Semaphore - could you ask someone to investigate that for you?

**Comment by neiljerram** [comment]
@coutinhop @fasaxc thinks it might be just a matter of clicking a "rescan teams" button in Semaphore, and he will do that shortly.

**Comment by coutinhop** [comment]
Thanks, @neiljerram! I had not noticed that!

**Pull request merged**
